import {download} from '../download.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statuses={submitted:'접수 완료',reviewing:'운영자 검토 중',needs_info:'자료 보완 필요',recheck_requested:'재검토 요청',completed:'최종 리포트 도착'};
const date=value=>new Date(value).toLocaleString('ko-KR');
async function api(path,input){const response=await fetch(path,input===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const data=await response.json();if(!response.ok)throw new Error(data.error||'요청을 처리하지 못했습니다.');return data;}
const area=(name,label,value='',min=0,max=5000)=>`<label>${label}<textarea name="${name}" rows="6" minlength="${min}" maxlength="${max}" ${min?'required':''}>${esc(value)}</textarea></label>`;
const block=(label,text)=>`<section class="private-block"><h3>${label}</h3><div class="private-text">${esc(text||'첨부하지 않았습니다.')}</div></section>`;
function submit(form,action){let dirty=false;form.addEventListener('input',()=>dirty=true);window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});form.addEventListener('submit',async event=>{event.preventDefault();const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);const error=form.querySelector('[role="alert"]');error.textContent='';try{const data=Object.fromEntries(new FormData(form));await action(data,event.submitter?.value);}catch(e){error.textContent=e.message+' 입력 내용은 유지됩니다.';}finally{buttons.forEach(b=>b.disabled=false);}});return ()=>dirty=false;}
export async function setupAccountNav(){const link=document.querySelector('a[data-account]');if(!link)return;try{const {user}=await api('/api/auth/me');if(!user)return;link.textContent=user.role==='operator'?'운영자 검토실':'마이페이지';link.href=user.role==='operator'?'/operator':'/my';const button=document.createElement('button');button.className='account-logout';button.textContent='로그아웃';button.addEventListener('click',async()=>{button.disabled=true;try{await api('/api/auth/logout',{});sessionStorage.removeItem('jasujeong-review-draft');location.assign('/login');}catch{button.textContent='로그아웃 재시도';button.disabled=false;}});link.after(button);}catch{}}
export async function mountPrivate(content){
 const path=location.pathname,params=new URLSearchParams(location.search),operator=path==='/operator';
 const title=({'/login':'로그인','/signup':'회원가입','/verify':'이메일 인증','/my':'마이페이지','/request':'비공개 첨삭 접수','/operator':'운영자 검토실'})[path];document.title=title+' | 자수정';
 content.innerHTML=`<section class="page-intro"><p class="eyebrow">자수정 · 비공개 검토</p><h1>${title}</h1><p>자료는 요청한 고객과 운영자만 확인합니다.</p></section><div id="private-view" aria-live="polite">불러오는 중입니다.</div>`;
 const view=document.getElementById('private-view');
 try{
 if(path==='/login'||path==='/signup'){
  const signup=path==='/signup',next=['/request','/my','/operator','/board?write=1'].includes(params.get('next'))?params.get('next'):'';
  const {signupAvailable}=signup?await api('/api/auth/config'):{signupAvailable:true};
  view.innerHTML=`<form class="private-form auth-form"><h2>${signup?'내 계정 만들기':'이메일로 로그인'}</h2>${signup?'<label>이름<input name="name" maxlength="30" autocomplete="name" required></label>':''}<label>이메일<input name="email" type="email" maxlength="254" autocomplete="username" required></label><label>비밀번호<input name="password" type="password" minlength="10" maxlength="128" autocomplete="${signup?'new-password':'current-password'}" required></label>${signup?'<label>비밀번호 확인<input name="passwordConfirm" type="password" minlength="10" maxlength="128" autocomplete="new-password" required></label>':''}<p class="muted">${signup?'비밀번호는 10자 이상으로 설정해 주세요.':'가입한 계정으로 진행 상태와 리포트를 확인하세요.'}</p><button ${signup&&!signupAvailable?'disabled':''}>${signup?'회원가입':'로그인'}</button><p role="alert">${signup&&!signupAvailable?'이메일 발송 설정 전에는 새 계정을 만들 수 없습니다.':''}</p><a href="${signup?'/login':'/signup'}${next?'?next='+encodeURIComponent(next):''}">${signup?'이미 계정이 있어요':'계정이 없어요 · 회원가입'}</a></form>`;
  const form=view.querySelector('form');let clean;
  clean=submit(form,async data=>{
   if(signup){if(data.password!==data.passwordConfirm)throw new Error('비밀번호 확인이 일치하지 않습니다.');await api('/api/auth/register',data);clean();view.innerHTML='<section class="private-block"><h2>인증 메일을 확인해 주세요.</h2><p>이메일의 인증 링크를 연 뒤 로그인할 수 있습니다. 링크는 24시간 동안 유효합니다.</p><a href="/verify">인증 메일을 다시 받아야 하나요?</a></section>';return;}
   const signed=await api('/api/auth/login',data);clean();location.assign(next||(signed.user.role==='operator'?'/operator':'/my'));
  });return;
 }
 if(path==='/verify'){
  const token=params.get('token');
  view.innerHTML=`${token?'<form id="verify-form" class="private-form"><h2>이메일 주소 인증</h2><p>가입을 완료하려면 아래 버튼을 눌러 주세요.</p><button>이메일 인증 완료하기</button><p role="alert"></p></form>':'<p>메일에 담긴 인증 링크를 열어 주세요.</p>'}<form id="resend-form" class="private-form"><h2>인증 메일 다시 받기</h2><label>가입한 이메일<input name="email" type="email" maxlength="254" required></label><button>인증 메일 보내기</button><p role="alert"></p></form>`;
  if(token)submit(view.querySelector('#verify-form'),async()=>{await api('/api/auth/verify',{token});history.replaceState(null,'','/verify');view.querySelector('#verify-form').innerHTML='<h2>인증이 완료됐습니다.</h2><a href="/login">로그인하기 →</a>';});
  submit(view.querySelector('#resend-form'),async(data)=>{await api('/api/auth/resend',data);view.querySelector('#resend-form [role="alert"]').textContent='인증이 필요한 계정이라면 메일을 다시 보냈습니다. 받은편지함을 확인해 주세요.';});return;
 }
 const {user}=await api('/api/auth/me');
 if(!user){location.replace('/login?next='+encodeURIComponent(path));return;}
 if(operator&&user.role!=='operator'){view.innerHTML='<h2>운영자만 이용할 수 있는 공간입니다.</h2><a href="/my">내 요청 확인하기</a>';return;}
 if(path==='/request'){
  let draft={};try{const saved=JSON.parse(sessionStorage.getItem('jasujeong-review-draft')||'null');if(saved&&typeof saved.essay==='string'&&typeof saved.aiReport==='string')draft=saved;}catch{}
  view.innerHTML=`<form class="private-form"><h2>어떤 부분을 검토해 드릴까요?</h2><p>AI 결과가 없어도 접수할 수 있습니다. 연락처 등 불필요한 개인정보는 제외해 주세요.</p><label>서비스<select name="service"><option value="resume">자소서 첨삭</option><option value="job-fit">직무 연결</option><option value="interview">텍스트 모의면접</option><option value="complete">통합 점검</option></select></label><label>요청 제목<input name="title" minlength="2" maxlength="100" placeholder="예: 지원 동기와 경험 전달력을 검토해 주세요" required></label><div class="private-toolbar"><label>지원 회사<input name="company" maxlength="100"></label><label>지원 직무<input name="role" maxlength="100"></label><label>제출 마감일<input name="deadline" type="date"></label></div>${area('essay','자소서 원문 또는 경험·면접 자료',draft.essay,20,12000)}${area('aiReport','AI 첨삭 결과 (선택)',draft.aiReport,0,20000)}${area('note','운영자에게 요청할 내용',draft.note,2)}<label class="private-check"><input type="checkbox" name="consent" required>검토를 위해 자료를 서버에 저장하고 운영자가 열람하는 데 동의합니다.</label><div class="private-toolbar"><button type="button" id="save-draft">임시 저장</button><button>비공개로 접수하기</button></div><p role="alert"></p></form>`;
  const form=view.querySelector('form');if(form.elements.service&&draft.service)form.elements.service.value=draft.service;const draftId=params.get('draft');if(draftId){const {drafts}=await api('/api/drafts');const saved=drafts.find(item=>item.id===draftId);if(saved)for(const [key,value] of Object.entries(saved))if(form.elements[key]&&form.elements[key].type!=='checkbox')form.elements[key].value=value;}
  form.querySelector('#save-draft').addEventListener('click',async()=>{const message=form.querySelector('[role="alert"]');try{const data=Object.fromEntries(new FormData(form));const saved=await api('/api/drafts',{...data,id:draftId,action:'save'});message.textContent='임시 저장했습니다.';history.replaceState(null,'','/request?draft='+encodeURIComponent(saved.draft.id));}catch(e){message.textContent=e.message;}});
  let clean;clean=submit(form,async data=>{const result=await api('/api/requests',{...data,consent:form.elements.consent.checked});try{sessionStorage.removeItem('jasujeong-review-draft');sessionStorage.removeItem(`jasujeong-workspace-draft-${data.service}`);}catch{}clean();location.assign('/my?id='+encodeURIComponent(result.request.id));});return;
 }
 const destination=operator?'/operator':'/my';
 if(!params.has('id')){
  const [{requests},{drafts},{notifications}]=await Promise.all([api('/api/requests'),api('/api/drafts'),api('/api/notifications')]);
  view.innerHTML=`<div class="private-toolbar"><p>${esc(user.name)}님 · ${requests.length}건의 요청</p><a class="button" href="/request">비공개 첨삭 접수하기 →</a>${user.role==='operator'?'<a href="/operator">운영자 검토실</a>':''}</div><div class="private-counts">${Object.entries(statuses).map(([key,label])=>`<div><span>${label}</span><strong>${requests.filter(r=>r.status===key).length}</strong></div>`).join('')}</div><section class="private-block"><h2>새 알림</h2>${notifications.filter(n=>!n.read).slice(0,10).map(n=>`<p><a href="${destination}?id=${encodeURIComponent(n.requestId)}">${esc(n.text)}</a> · ${date(n.at)} <button type="button" data-read="${esc(n.id)}">읽음</button></p>`).join('')||'<p>새 알림이 없습니다.</p>'}</section>${!operator?`<section class="private-block"><h2>작성 중인 자료</h2>${drafts.map(d=>`<p><a href="/request?draft=${encodeURIComponent(d.id)}">${esc(d.title)}</a> · ${esc(d.company||'회사 미입력')} ${esc(d.role||'')} ${d.deadline?'· 마감 '+esc(d.deadline):''}</p>`).join('')||'<p>임시 저장한 자료가 없습니다.</p>'}</section>`:''}<ul class="private-list">${requests.map(r=>`<li><a href="${destination}?id=${encodeURIComponent(r.id)}"><span class="tag">${statuses[r.status]||esc(r.status)}</span><h2>${esc(r.title)}</h2><p>${operator?esc(r.ownerName)+' · ':''}${esc(r.company||'')} ${esc(r.role||'')} ${r.deadline?'· 마감 '+esc(r.deadline):''} · ${date(r.updatedAt)} 업데이트${r.dueAt?' · 검토 예정 '+esc(r.dueAt):''}</p><span>상세 보기 →</span></a></li>`).join('')}</ul>${requests.length?'':'<p class="no-results">아직 접수한 요청이 없습니다. 첫 요청을 남겨 보세요.</p>'}${operator?'<section class="private-block"><h2>이전 공개 첨삭 요청</h2><p>작성자 계정을 확인할 수 없어 고객 계정에 임의로 연결하지 않습니다. 기존 원본은 보존되며 운영자만 확인합니다.</p><button id="legacy">기존 요청 확인</button><div id="legacy-list"></div></section>':''}`;
  if(user.role!=='operator'){
   const section=document.createElement('section');section.className='private-block account-delete';
   section.innerHTML='<details><summary>계정 및 내 자료 삭제</summary><p>계정, 비공개 접수·임시 저장·알림, 내가 쓴 게시글·댓글·신고를 현재 서비스 저장소에서 삭제합니다. 삭제 후에는 복구할 수 없습니다.</p><form class="private-form"><label>현재 비밀번호<input name="password" type="password" autocomplete="current-password" required></label><label class="private-check"><input name="confirm" type="checkbox" required>삭제 범위를 확인했습니다.</label><button type="submit">계정과 자료 삭제하기</button><p role="alert"></p></form></details>';
   view.append(section);
   const form=section.querySelector('form');form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;const button=form.querySelector('button'),message=form.querySelector('[role="alert"]');button.disabled=true;try{await api('/api/account/delete',{password:form.elements.password.value});try{for(const key of Object.keys(sessionStorage))if(key.startsWith('jasujeong-'))sessionStorage.removeItem(key);}catch{}location.assign('/');}catch(error){message.textContent=error.message;button.disabled=false;}});
  }
  view.querySelectorAll('[data-read]').forEach(button=>button.addEventListener('click',async()=>{try{await api('/api/notifications/read',{id:button.dataset.read});button.parentElement.remove();}catch(e){button.textContent=e.message;}}));
  if(operator)view.querySelector('#legacy').addEventListener('click',async event=>{event.target.disabled=true;const list=view.querySelector('#legacy-list');try{const {posts}=await api('/api/legacy-requests');list.innerHTML=posts.length?posts.map(p=>`<details><summary>${esc(p.title)}</summary>${block('기존 닉네임 (미인증)',p.author)}${block('요청사항',p.body)}${block('원문',p.essay)}${block('AI 결과',p.aiReport)}</details>`).join(''):'보관된 이전 요청이 없습니다.';}catch(e){list.textContent=e.message;}finally{event.target.disabled=false;}});return;
 }
 const {request:r}=await api('/api/requests?id='+encodeURIComponent(params.get('id')));
 view.innerHTML=`<a href="${destination}">← 요청 목록</a><div class="private-toolbar"><h2>${esc(r.title)}</h2><span class="tag">${statuses[r.status]||esc(r.status)}</span></div><p class="muted">${esc(r.company||'회사 미입력')} · ${esc(r.jobRole||'직무 미입력')} ${r.deadline?'· 제출 마감 '+esc(r.deadline):''} ${r.dueAt?'· 검토 예정 '+esc(r.dueAt):''}<br>접수 ${date(r.createdAt)} · 최근 변경 ${date(r.updatedAt)}</p><p class="private-progress">접수 → 운영자 검토 → 필요 시 자료 보완 → 최종 리포트</p><div class="private-columns"><article>${block('제출 자료 원문',r.essay)}${block('AI 결과',r.aiReport)}${block('고객 요청사항',r.note)}<section class="private-block"><h3>보완·재검토 대화</h3>${r.messages.length?r.messages.map(m=>block(m.by==='operator'?'운영자 · '+date(m.at):'고객 · '+date(m.at),m.text)).join(''):'아직 대화가 없습니다.'}</section><section class="private-block" id="interview-panel"><h3>운영자 텍스트 모의면접</h3></section></article><aside id="review-panel"></aside></div>`;
 const interview=view.querySelector('#interview-panel');const turns=r.interview?.turns||[];const last=turns.at(-1);
 interview.innerHTML+=`${turns.map((turn,i)=>`<div class="private-block"><h4>${i+1}번째 질문</h4>${block('운영자 질문',turn.question)}${turn.answer?block('내 답변',turn.answer):''}${turn.followUp?block('꼬리 질문',turn.followUp):''}${turn.followUpAnswer?block('꼬리 질문 답변',turn.followUpAnswer):''}</div>`).join('')}${r.interview?.feedback?block('최종 면접 피드백',r.interview.feedback):''}`;
 let action='',prompt='';if(operator&&r.status!=='completed'){if(!last||last.answer&&(!last.followUp||last.followUpAnswer)){action='question';prompt='다음 면접 질문';}else if(last.answer&&!last.followUp){action='followup';prompt='꼬리 질문';}if(last?.answer&&(!last.followUp||last.followUpAnswer)){interview.insertAdjacentHTML('beforeend','<button type="button" id="feedback-button">최종 피드백 작성</button>');}}
 if(!operator&&last){if(!last.answer){action='answer';prompt='면접 답변';}else if(last.followUp&&!last.followUpAnswer){action='followup_answer';prompt='꼬리 질문 답변';}}
 if(action)interview.insertAdjacentHTML('beforeend',`<form class="private-form" id="interview-form"><h4>${prompt}</h4>${area('text',prompt,'',2,5000)}<button>전송</button><p role="alert"></p></form>`);
 const sendInterview=async (text,kind)=>{await api('/api/requests/interview',{id:r.id,version:r.version,action:kind,text});location.reload();};
 if(action)submit(interview.querySelector('#interview-form'),data=>sendInterview(data.text,action));
 interview.querySelector('#feedback-button')?.addEventListener('click',()=>{interview.querySelector('#feedback-button').outerHTML=`<form class="private-form" id="feedback-form">${area('text','최종 피드백','',10,5000)}<button>피드백 전달</button><p role="alert"></p></form>`;submit(interview.querySelector('#feedback-form'),data=>sendInterview(data.text,'feedback'));});
 const panel=view.querySelector('#review-panel');
 if(r.status==='completed'){
  panel.innerHTML=`<section class="private-block"><h2>최종 첨삭 리포트</h2><p>${esc(r.final.reviewer)} 운영자 · ${date(r.completedAt)}</p>${r.finalHistory?.length?block('재검토 전 수정본',r.finalHistory.at(-1).revision):''}${block('수정본',r.final.revision)}${block('수정 이유',r.final.reason)}${block('다음 준비와 보완점',r.final.next)}<button id="download-final">최종 리포트 다운로드</button></section>`;
  if(!operator)panel.insertAdjacentHTML('beforeend',r.recheckCount?'<p>재검토 요청 1회를 사용했습니다.</p>':`<form class="private-form" id="recheck-form"><h3>수정 내용 질문·재검토 요청</h3>${area('message','궁금한 점 또는 재검토할 부분','',2,5000)}<button>재검토 요청</button><p role="alert"></p></form>`);
  panel.querySelector('#download-final').addEventListener('click',()=>download(`${r.title}\n검토자: ${r.final.reviewer}\n\n원문\n${r.essay}\n\n수정본\n${r.final.revision}\n\n수정 이유\n${r.final.reason}\n\n다음 준비와 보완점\n${r.final.next}`,'자수정-최종리포트.txt'));
  if(!operator&&!r.recheckCount)submit(panel.querySelector('#recheck-form'),async data=>{await api('/api/requests/recheck',{id:r.id,version:r.version,message:data.message});location.reload();});return;
 }
 if(operator){
  panel.innerHTML=`${r.final?block('이전 수정본',r.final.revision):''}<form class="private-form"><h2>운영자 2차 검토</h2><p>임시 수정본은 고객에게 표시되지 않습니다. 최종 제출 후 고객이 리포트를 확인할 수 있습니다.</p><label>검토 예정일<input type="date" name="dueAt" value="${esc(r.dueAt||'')}"></label>${area('revision','수정본',r.draft.revision,0,20000)}${area('reason','수정 이유',r.draft.reason)}${area('next','다음 준비와 보완점',r.draft.next)}${area('message','고객에게 보완 요청 (보완 요청 시 필수)')}<label class="private-check"><input name="checked" type="checkbox">원문에 없는 사실을 추가하지 않았으며 최종 내용을 확인했습니다.</label><p class="muted">최종 제출 시 수정본·수정 이유·보완점을 각각 20자 이상 작성해 주세요.</p><div class="private-toolbar"><button value="reviewing">임시 저장 · 검토 중</button><button value="needs_info">자료 보완 요청</button><button value="completed">최종 리포트 제출</button></div><p role="alert"></p></form>`;
  const form=panel.querySelector('form');let clean;clean=submit(form,async(data,status)=>{if(status==='completed'&&!confirm('고객에게 최종 리포트를 전달할까요? 제출 후 수정할 수 없습니다.'))return;await api('/api/requests/update',{...data,id:r.id,version:r.version,status,checked:form.elements.checked.checked});clean();location.reload();});
 }else if(r.status==='needs_info'){
  panel.innerHTML=`<form class="private-form"><h2>추가 자료를 알려주세요.</h2><p>운영자의 질문을 확인하고 답변하면 다시 검토 대기 상태로 변경됩니다.</p>${area('message','보완 답변','',2)}<button>답변 보내기</button><p role="alert"></p></form>`;
  let clean;clean=submit(panel.querySelector('form'),async data=>{await api('/api/requests/reply',{...data,id:r.id,version:r.version});clean();location.reload();});
 }else panel.innerHTML=`<section class="private-block"><h2>${r.status==='recheck_requested'?'재검토를 기다리고 있어요.':'운영자의 검토를 기다리고 있어요.'}</h2>${r.final?block('이전 리포트 수정본',r.final.revision):''}<p>보완 요청이나 최종 리포트는 이 페이지에서 확인하세요.</p><a href="${esc(location.pathname+location.search)}">진행 상태 새로고침</a></section>`;
 }catch(e){view.innerHTML=`<p role="alert">${esc(e.message)}</p><a href="/login">다시 로그인</a> · <a href="${esc(location.pathname+location.search)}">다시 불러오기</a>`;}
}
